# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fabio Papa – Full-Stack Web Developer
email: me@fabiopapa.dev
phone: +1 (778) 230-5559
description: >- # this means to ignore newlines until "baseurl:"
  Software developer with over 15 years of experience in **full-stack** web
  development, with a strong focus on _Ruby on Rails_ and _React_. Believes
  deeply in finding the simplest-possible solution, and iterating over it until
  an elegant, joy-eliciting solution emerges. Passionate about clean, readable
  code that communicates intent, _test-driven-_ and _behavior-driven-design_,
  and clean user interfaces.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.fabiopapa.dev" # the base hostname & protocol for your site, e.g. http://example.com
gitlab_username: fapapa
github_username: fapapa
linkedin_username: fabio-papa-dev

# Build settings
markdown: kramdown
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
